# Generated by Django 4.0.1 on 2022-01-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
